

export const SIDEBAR_OPEN='SIDEBAR_OPEN'
export const SIDEBAR_CLOSE='SIDEBAR_CLOSE'
export const GET_PRODUCT_BEGIN=' GET_PRODUCT_BEGIN'
export const GET_PRODUCT_SUCESS='GET_PRODUCT_SUCESS'
export const GET_PRODUCT_ERROR='GET_PRODUCT_ERROR'
